repos:
- repo: local
  hooks:
  - id: black
    name: Format Python code with Black
    entry: poetry run black
    language: system
    types: [python]

  - id: isort
    name: Sort Python imports with isort
    entry: poetry run isort
    language: system
    types: [python]
